import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens
        'inverse-surface': '#2d3133',
        'on-surface-variant': '#444651',
        'on-surface': '#191c1e',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'on-secondary-fixed-variant': '#3a485b',
        'tertiary': '#002114',
        'secondary-fixed': '#d5e3fc',
        'surface-dim': '#d8dadc',
        'secondary-fixed-dim': '#b9c7df',
        'primary': '#001a48',
        'primary-container': '#002d72',
        'inverse-primary': '#b1c5ff',
        'surface-tint': '#3d5ca2',
        'on-tertiary-container': '#00ae79',
        'on-error': '#ffffff',
        'surface': '#f7f9fb',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e3fc',
        'secondary': '#515f74',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#6ffbbe',
        'outline': '#747782',
        'on-primary-fixed-variant': '#224489',
        'on-primary-fixed': '#001946',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#4edea3',
        'background': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c4c6d2',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-container': '#57657a',
        'tertiary-container': '#003925',
        'primary-fixed-dim': '#b1c5ff',
        'on-tertiary-fixed-variant': '#005236',
        'surface-variant': '#e0e3e5',
        'surface-container-highest': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed': '#002113',
        'on-primary-container': '#7a97e2',
        'primary-fixed': '#b1c5ff',
        // Semantic aliases kept for compatibility
        'ok': '#00ae79',
        'ok-soft': '#e7f5ee',
        'warn': '#A65A06',
        'warn-soft': '#FBF1E2',
        'danger': '#ba1a1a',
        'danger-soft': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      boxShadow: {
        'card': '0 8px 24px rgba(0,26,72,0.04)',
        'sm': '0 1px 3px rgba(0,0,0,0.06)',
        'primary': '0 4px 14px rgba(0,26,72,0.25)',
      },
    },
  },
  plugins: [],
}
export default config
